### ISSUE TITLE
Cannot train model on custom dataset.

### ISSUE THREAD

**Issue by KirylLapouski** [bhrnjica/ObjectDetection#1]
I use VOTT to mark my dataset, and replace nokia3310 dataset to my custom dataset. After running `Nokia3310_detection` i get this
![image](https://user-images.githubusercontent.com/29763516/37314329-8c0e5230-2664-11e8-9b14-85cbc09bb53d.png)
How can i fix it?

**Comment by bhrnjica** [comment]
As I can see from the Exception Call stack the problem is in bounding boxes of region of interest (roi). Check if all positive images have at least one roi,

**Comment by KirylLapouski** [comment]
Hi, thanks a lot for your work. I fix this problem by setting same widths and heights for all images (positive, negative, testImages).
